export default [
    {
        memberId: "0001",
        firstName: "นม",
        lastName: "เปรี้ยว",
        gender: "ชาย",
        phoneNumber: "0899999999",
        email: "dutchmilk@email.com",
        memberTier: "ธรรมดา",
    },
    {
        memberId: "0002",
        firstName: "Frozen",
        lastName: "Yogurt",
        gender: "หญิง",
        phoneNumber: "0899999999",
        email: "dutchmilk@email.com",
        memberTier: "พรีเมี่ยม",
    },
    {
        memberId: "0003",
        fname: "จอห์น",
        lastName: "ดอว์",
        gender: "ชาย",
        phoneNumber: "0899999999",
        email: "john@lnwza.com",
        memberTier: "เจ้าของ",
    },
    {
        memberId: "0004",
        firstName: "Frozen",
        lastName: "Yogurt",
        gender: "หญิง",
        phoneNumber: "0899999999",
        email: "dutchmilk@email.com",
        memberTier: "แอดมิน",
    },
    {
        memberId: "0005",
        firstName: "wefgwer",
        lastName: "wegweg",
        gender: "หญิง",
        phoneNumber: "0899999999",
        email: "dutchmilk@email.com",
        memberTier: "ธรรมดา",
    },
];